prac_compo: ejer4-1.cpp Rectangulo.o
	g++ ejer4-1.cpp Rectangulo.o Coordenada.o -o ejer4-1
Rectangulo.o: Rectangulo.cpp Coordenada.o Rectangulo.h
	g++ Rectangulo.cpp -c
Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c
